### ISSUE TITLE
Síntesis 

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-3-sintesis-Irvingzr16#1]
[Sintesis - IZR.pdf](https://github.com/user-attachments/files/16820638/Sintesis.-.IZR.pdf)

**Comment by Arlet04** [comment]
Preparación e identificación: muy bien 30
Estructura: 60
Presentación: 10
Calificación: 100

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
